#!/bin/bash
# Quick Reference - Production Deployment Commands

echo "================================"
echo "FP Digital Publisher - Production Deployment"
echo "================================"
echo ""
echo "1. BUILD PRODUCTION ASSETS"
echo "   cd fp-digital-publisher && npm run build:prod"
echo ""
echo "2. DEPLOY STANDARD (creates ZIP)"
echo "   cd fp-digital-publisher && ./deploy.sh --version=0.2.0"
echo ""
echo "3. DEPLOY WITH DOCKER"
echo "   cd fp-digital-publisher && ./deploy.sh --version=0.2.0 --docker"
echo ""
echo "4. DEPLOY TO DIRECTORY"
echo "   cd fp-digital-publisher && ./deploy.sh --version=0.2.0 --target=/path/to/wordpress/plugins"
echo ""
echo "5. BUILD DOCKER IMAGE MANUALLY"
echo "   docker build -f Dockerfile.production -t fp-digital-publisher:production ."
echo ""
echo "6. SECURITY AUDIT"
echo "   cd fp-digital-publisher && composer audit && npm audit --omit=dev"
echo ""
echo "7. VERIFY PRODUCTION BUILD"
echo "   cd fp-digital-publisher"
echo "   ls assets/dist/admin/*.map 2>/dev/null || echo '✓ No sourcemaps'"
echo "   grep -c 'console\.' assets/dist/admin/index.js || echo '✓ No console statements'"
echo ""
echo "================================"
