version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - wp_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  wordpress:
    image: wordpress:6.6-php8.1-apache
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "1"
    volumes:
      - ./fp-digital-publisher:/var/www/html/wp-content/plugins/fp-digital-publisher:rw
      - wp_wp_content:/var/www/html/wp-content

  wpcli:
    image: wordpress:cli-php8.1
    depends_on:
      wordpress:
        condition: service_started
    user: root
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./fp-digital-publisher:/var/www/html/wp-content/plugins/fp-digital-publisher:rw
      - wp_wp_content:/var/www/html/wp-content

volumes:
  wp_mysql_data:
  wp_wp_content:


