name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: PHP Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        working-directory: fp-digital-publisher
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit (Unit)
        working-directory: fp-digital-publisher
        run: vendor/bin/phpunit -c phpunit.xml.dist --testsuite Unit

  smoke-tests:
    name: Smoke Tests (Docker)
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version || sudo apt-get update && sudo apt-get install -y docker-compose-plugin

      - name: Start stack
        run: docker compose -f docker-compose.yml up -d

      - name: Install Composer in container
        run: docker compose -f docker-compose.yml exec -T wordpress sh -lc "cd /var/www/html/wp-content/plugins/fp-digital-publisher && composer install --no-interaction --prefer-dist"

      - name: Activate plugin
        run: docker compose -f docker-compose.yml exec -T wordpress wp plugin activate fp-digital-publisher --allow-root

      - name: Health endpoint
        run: |
          RES=$(docker compose -f docker-compose.yml exec -T wordpress sh -lc "curl -s http://localhost:8080/wp-json/fp-publisher/v1/health")
          echo "$RES"
          echo "$RES" | jq -e '.status == "healthy"'

      - name: Diagnostics (queue)
        run: docker compose -f docker-compose.yml exec -T wordpress wp fp-publisher diagnostics --component=queue --allow-root

      - name: Enqueue test job and run
        run: |
          docker compose -f docker-compose.yml exec -T wordpress wp eval "\\FP\\Publisher\\Infra\\Queue::enqueue('wordpress_blog', ['plan'=>['title'=>'Hello','content'=>'World']], new DateTimeImmutable('now', new DateTimeZone('UTC')), 'ci_' . time());" --allow-root
          docker compose -f docker-compose.yml exec -T wordpress wp fp-publisher queue run --limit=5 --allow-root

      - name: Stop stack
        if: always()
        run: docker compose -f docker-compose.yml down -v


